layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  linkedin: noah-bond-007
  # medium: @your_username
  # stackoverflow: your_user_id
  # twitter: your_username
  # youtube: your_username

topics:
  - name: Kotlin Multiplatform
    web_url: https://github.com/topics/kotlin-multiplatform
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/kotlin/kotlin.png

  - name: Android
    web_url: https://github.com/topics/android
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/android/android.png

  - name: Strongman
    web_url: https://www.strongmancorporation.com/
    image_url: https://pbs.twimg.com/profile_images/775813705715949570/ToycrwcH_400x400.jpg

  - name: Singing
    web_url: https://sites.google.com/view/singannarbor/home
    image_url: https://tse1.mm.bing.net/th?id=OIP.DqSeYtdaXsdY_PBwhY6DKgAAAA&w=190&h=238&c=8&o=5&pid=1.7

  - name: iOS
    web_url: https://github.com/topics/ios
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/ios/ios.png
